### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'users'

### ISSUE THREAD

**Issue by cyber-urvesh** [amiryousefi/telegram-analysis#1]
When I execute the following command:

`python3 ChannelUsers.py `
It gives the following error: 

ChannelUsers.py:30: RuntimeWarning: coroutine 'UserMethods.is_user_authorized' was never awaited
  if not client.is_user_authorized():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
enter entity(telegram URL or entity id):Web HackZ
Traceback (most recent call last):
  File "ChannelUsers.py", line 57, in <module>
    if not participants.users:
AttributeError: 'coroutine' object has no attribute 'users'
sys:1: RuntimeWarning: coroutine 'UserMethods.get_me' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'UserMethods.__call__' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Also please tell, exactly what is Entity Id or Telegram URL ? What are we supposed to write for that parameter.

**Comment by pdelteil** [comment]
Same issue here!

**Comment by pdelteil** [comment]
I fixed it adding this import:

import telethon.sync

**Comment by amiryousefi** [comment]
Thank you @pdelteil 
I'll give it a try and add it to the code.
Also, if you make a pull request I can merge it with the master 👍

**Comment by k-oktavius** [comment]
Hi,
the same error happened to me and unfortunately importing telethon. sync didn't help.
do you have any other solution?
I have searched the web to find a solution but found any.

**Comment by deraswer** [comment]
Check my pull-request, plz. It solve this issue very well

**Comment by amiryousefi** [comment]
Thanks to @deraswer pull request(https://github.com/amiryousefi/telegram-analysis/pull/4), the issue is now solved.
It is merged into master.

**Comment by Keramatfar** [comment]
> import telethon.sync

does not work.

**Comment by devendrachandora** [comment]
New File also does not Work

**Comment by xectrone** [comment]
> > import telethon.sync
> 
> does not work.

nope :(
