### ISSUE TITLE
how to bypass this problem

### ISSUE THREAD

**Issue by DudeAj** [amiryousefi/telegram-analysis#10]
ChatAdminRequiredError: Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)

**Comment by knowledgecomputer2018** [comment]
him
i have this problem!!!!
but with i have not this problem .
god willing

**Comment by amiryousefi** [comment]
It may occur if you use this code on a private channel or group.
