### ISSUE TITLE
Is there a way to pass multiple Telegram channels?

### ISSUE THREAD

**Issue by seekerseek** [amiryousefi/telegram-analysis#11]
Huge thanks to @amiryousefi! Superior tool!

However, does anyone know if there is a way to pass multiple Telegram channels into the ChannelMessages? 

So, the way one JSON file would contain messages from 10+ TG channels? Should be ok given the structure of JSON is the same across all channels. 

Thank you!

**Comment by amiryousefi** [comment]
Need an extra loop to go through all channels. I'll appreciate it if somebody could do a pull request for that if other people found this helpful.
