### ISSUE TITLE
Hint: Telegram groups are actually channels, too.. members and messages can be extracted, iff..

### ISSUE THREAD

**Issue by bufemc** [amiryousefi/telegram-analysis#6]
I was wondering how to get members of a group, because this script has the file named ChannelUsers.py .. Then I found out groups are actually "improved" channels with just an extra attribute .megagroup = True

So it's possible to get also members from a group with ChannelUsers.py or messages from a group with ChannelMessages.py. IFF they are public. This could be said more clear.

1. Group members can be extracted IFF the group is public. Most are private!

2. Group messages can be extracted IFF the group is public. But: if it was first private, and then changed to public later, the extract will only contain the messages after it was changed to public, missing the messages when it still was private (nice feature!)

Same goes I guess for channels, they have to be public.

To close this "issue" maybe we could just improve the README, explaining this?

**Comment by amiryousefi** [comment]
I checked the code recently and just added a note on the README file.
Also, I created a video tutorial where I explain this alongside how to use this code.
://www.youtube.com/watch?v=aU1p-F7gDo4&ab_channel=AmirYousefi
