### ISSUE TITLE
How to get last message from history = client(GetHistoryRequest())

### ISSUE THREAD

**Issue by Ikram24817** [amiryousefi/telegram-analysis#7]
How to get last message from history, How to automate the script, to get the latest message from the channel as soon as we receive in the channel.
history = client(GetHistoryRequest(
        peer=my_channel,
        offset_id=offset_id,
        offset_date=None,
        add_offset=0,
        limit=limit,
        max_id=0,
        min_id=0,
        hash=0
    ))

Thanks
Ikram

**Comment by amiryousefi** [comment]
This one is a bit old but for anybody else who might ask the same question:
To my knowledge, you need a bot for that and/or utilizing Telegram webhooks.
